[client]
# Disable the ability to show the "Deploy" button in the toolbar
showErrorDetails = true
toolbarMode = "minimal"

[ui]
# Hide the hamburger menu "Deploy" option
hideTopBar = false

[browser]
# Don't automatically open browser on server start
gatherUsageStats = false

[server]
# Enable CORS for production
enableCORS = true
enableXsrfProtection = true

[theme]
# Optional: You can customize the theme here if needed
# primaryColor = "#F63366"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"
# font = "sans serif"

[deployButton]
# This is the key setting to hide the Deploy button
show = false
